CREATE TABLE IF NOT EXISTS results (
    id SERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    r INTEGER NOT NULL,
    hit BOOLEAN NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    execution_time BIGINT NOT NULL
);
